name: Build and Release Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Binary
        run: cargo build --release

      - name: Rename Binary (Linux/macOS)
        if: runner.os != 'Windows'
        run: mv target/release/databoxer databoxer-${{ runner.os }}

      - name: Rename Binary (Windows)
        if: runner.os == 'Windows'
        run: ren target\release\databoxer.exe databoxer-${{ runner.os }}.exe

      - name: Upload Artifact (Linux/macOS)
        uses: actions/upload-artifact@v4
        with:
          name: databoxer-${{ runner.os }}
          path: |
            databoxer-${{ runner.os }}
            databoxer-${{ runner.os }}.exe

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
