name: MacOS Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build binary
      run: cargo build

    - name: Run tests
      run: cargo test -- --test-threads=1 --show-output
