name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update dependencies
      run: cargo update

    - name: Build binary
      run: cargo build --verbose --release

    - name: Run tests
      run: cargo test --verbose -- --test-threads=1 --show-output
